import AuditEventCard from "./AuditEventCard";


export default function AuditTimeline(){


const events=[

{
title:"Question Paper Created",
description:"Paper generated by Examination Authority",
time:"12 June 2026 | 09:30 AM",
status:"Verified"
},


{
title:"Printing Press Received",
description:"Transferred to secure printing facility",
time:"13 June 2026 | 11:15 AM",
status:"Verified"
},


{
title:"Packaging Completed",
description:"Encrypted package prepared for transport",
time:"15 June 2026 | 04:20 PM",
status:"Verified"
},


{
title:"Suspicious Access Detected",
description:"Unknown device accessed confidential paper data",
time:"18 June 2026 | 02:45 AM",
status:"Alert"
},


{
title:"Investigation Started",
description:"AI system initiated forensic investigation",
time:"18 June 2026 | 08:00 AM",
status:"Verified"
}


];


return(

<div className="bg-slate-50 p-6 rounded-xl">


<h2 className="text-xl font-bold text-slate-800 mb-6">
Paper Journey Timeline
</h2>



<div className="space-y-5">


{
events.map((event,index)=>(

<div key={index} className="relative">


<div className="absolute -left-3 top-6 w-3 h-3 bg-blue-600 rounded-full">
</div>


<AuditEventCard {...event}/>


</div>

))
}


</div>


</div>

)

}